Radek posted about this [here](https://www.kaggle.com/competitions/h-and-m-personalized-fashion-recommendations/discussion/309220), and linked to a GitHub repo with the code.

I just transferred that code here to Kaggle notebooks, that's all.

In [199]:
import numpy as np

def apk(actual, predicted, k=10):
    """
    Computes the average precision at k.

    This function computes the average prescision at k between two lists of
    items.

    Parameters
    ----------
    actual : list
             A list of elements that are to be predicted (order doesn't matter)
    predicted : list
                A list of predicted elements (order does matter)
    k : int, optional
        The maximum number of predicted elements

    Returns
    -------
    score : double
            The average precision at k over the input lists

    """
    if len(predicted)>k:
        predicted = predicted[:k]

    score = 0.0
    num_hits = 0.0

    for i,p in enumerate(predicted):
        if p in actual and p not in predicted[:i]:
            num_hits += 1.0
            score += num_hits / (i+1.0)

    if not actual:
        return 0.0

    return score / min(len(actual), k)

def mapk(actual, predicted, k=10):
    """
    Computes the mean average precision at k.

    This function computes the mean average prescision at k between two lists
    of lists of items.

    Parameters
    ----------
    actual : list
             A list of lists of elements that are to be predicted 
             (order doesn't matter in the lists)
    predicted : list
                A list of lists of predicted elements
                (order matters in the lists)
    k : int, optional
        The maximum number of predicted elements

    Returns
    -------
    score : double
            The mean average precision at k over the input lists

    """
    return np.mean([apk(a,p,k) for a,p in zip(actual, predicted)])

In [200]:
from sklearn.base import BaseEstimator, TransformerMixin
import numpy as np

# https://www.kaggle.com/c/h-and-m-personalized-fashion-recommendations/discussion/308635
def customer_hex_id_to_int(series):
    return series.str[-16:].apply(hex_id_to_int)

def hex_id_to_int(str):
    return int(str[-16:], 16)

def article_id_str_to_int(series):
    return series.astype('int32')

def article_id_int_to_str(series):
    return '0' + series.astype('str')

class Categorize(BaseEstimator, TransformerMixin):
    def __init__(self, min_examples=0):
        self.min_examples = min_examples
        self.categories = []
        
    def fit(self, X):
        for i in range(X.shape[1]):
            vc = X.iloc[:, i].value_counts()
            self.categories.append(vc[vc > self.min_examples].index.tolist())
        return self

    def transform(self, X):
        data = {X.columns[i]: pd.Categorical(X.iloc[:, i], categories=self.categories[i]).codes for i in range(X.shape[1])}
        return pd.DataFrame(data=data)


def calculate_apk(list_of_preds, list_of_gts):
    # for fast validation this can be changed to operate on dicts of {'cust_id_int': [art_id_int, ...]}
    # using 'data/val_week_purchases_by_cust.pkl'
    apks = []
    for preds, gt in zip(list_of_preds, list_of_gts):
        apks.append(apk(gt, preds, k=12))
    return np.mean(apks)

def eval_sub(sub_csv, skip_cust_with_no_purchases=True):
    sub=pd.read_csv(sub_csv)
    validation_set=pd.read_parquet('data/validation_ground_truth.parquet')

    apks = []

    no_purchases_pattern = []
    for pred, gt in zip(sub.prediction.str.split(), validation_set.prediction.str.split()):
        if skip_cust_with_no_purchases and (gt == no_purchases_pattern): continue
        apks.append(apk(gt, pred, k=12))
    return np.mean(apks)

In [201]:
import pandas as pd

In [202]:
%%time

transactions = pd.read_parquet('../input/warmup/transactions_train.parquet')
customers = pd.read_parquet('../input/warmup/customers.parquet')
articles = pd.read_parquet('../input/warmup/articles.parquet')

# sample = 0.05
# transactions = pd.read_parquet(f'data/transactions_train_sample_{sample}.parquet')
# customers = pd.read_parquet(f'data/customers_sample_{sample}.parquet')
# articles = pd.read_parquet(f'data/articles_train_sample_{sample}.parquet')

CPU times: user 2.43 s, sys: 6.03 s, total: 8.46 s
Wall time: 7.14 s

In [203]:
test_week = transactions.week.max() + 1
transactions = transactions[transactions.week > transactions.week.max() - 10]

# Generating candidates

### Last purchase candidates

In [204]:
%%time

c2weeks = transactions.groupby('customer_id')['week'].unique()

CPU times: user 18.6 s, sys: 597 ms, total: 19.2 s
Wall time: 18.8 s

In [205]:
transactions.groupby('week')['t_dat'].agg(['min', 'max'])

            min        max
week
95   2020-07-15 2020-07-21
96   2020-07-22 2020-07-28
97   2020-07-29 2020-08-04
98   2020-08-05 2020-08-11
99   2020-08-12 2020-08-18
100  2020-08-19 2020-08-25
101  2020-08-26 2020-09-01
102  2020-09-02 2020-09-08
103  2020-09-09 2020-09-15
104  2020-09-16 2020-09-22

In [206]:
c2weeks

customer_id
28847241659200          [95, 96, 101, 102]
41318098387474                        [98]
116809474287335                 [101, 103]
200292573348128          [95, 96, 99, 102]
248294615847351                       [96]
                               ...
18446624797007271432                  [95]
18446630855572834764                 [103]
18446662237889060501                 [100]
18446705133201055310                 [102]
18446737527580148316                 [104]
Name: week, Length: 437365, dtype: object

In [207]:
%%time

c2weeks2shifted_weeks = {}

for c_id, weeks in c2weeks.items():
    c2weeks2shifted_weeks[c_id] = {}
    for i in range(weeks.shape[0]-1):
        c2weeks2shifted_weeks[c_id][weeks[i]] = weeks[i+1]
    c2weeks2shifted_weeks[c_id][weeks[-1]] = test_week

CPU times: user 1.01 s, sys: 205 ms, total: 1.21 s
Wall time: 1.22 s

In [208]:
c2weeks2shifted_weeks[28847241659200]

{95: 96, 96: 101, 101: 102, 102: 105}

In [209]:
candidates_last_purchase = transactions.copy()

In [210]:
%%time

weeks = []
for i, (c_id, week) in enumerate(zip(transactions['customer_id'], transactions['week'])):
    weeks.append(c2weeks2shifted_weeks[c_id][week])
    
candidates_last_purchase.week=weeks

CPU times: user 8.06 s, sys: 40.1 ms, total: 8.1 s
Wall time: 8.11 s

In [211]:
candidates_last_purchase[candidates_last_purchase['customer_id']==272412481300040]

,t_dat,customer_id,article_id,price,sales_channel_id,week
29030503,2020-07-15,272412481300040,778064028,0.008458,1,96
29030504,2020-07-15,272412481300040,816592008,0.016932,1,96
29030505,2020-07-15,272412481300040,621381021,0.033881,1,96
29030506,2020-07-15,272412481300040,817477003,0.025407,1,96
29030507,2020-07-15,272412481300040,899088002,0.025407,1,96
29319533,2020-07-22,272412481300040,885077001,0.008458,1,103
29410772,2020-07-24,272412481300040,850176003,0.029034,2,103
29410773,2020-07-24,272412481300040,875803001,0.064559,2,103
29410774,2020-07-24,272412481300040,892970003,0.020966,2,103
29410775,2020-07-24,272412481300040,854619003,0.020966,2,103
29531614,2020-07-27,272412481300040,900398001,0.030492,2,103
29531615,2020-07-27,272412481300040,834179002,0.025407,2,103
29531616,2020-07-27,272412481300040,875803001,0.067780,2,103
31495014,2020-09-14,272412481300040,923460002,0.039932,2,105
31495015,2020-09-14,272412481300040,922381001,0.039932,2,105
31495016,2020-09-14,272412481300040,921906005,0.031949,2,105

In [212]:
transactions[transactions['customer_id']==272412481300040]

,t_dat,customer_id,article_id,price,sales_channel_id,week
29030503,2020-07-15,272412481300040,778064028,0.008458,1,95
29030504,2020-07-15,272412481300040,816592008,0.016932,1,95
29030505,2020-07-15,272412481300040,621381021,0.033881,1,95
29030506,2020-07-15,272412481300040,817477003,0.025407,1,95
29030507,2020-07-15,272412481300040,899088002,0.025407,1,95
29319533,2020-07-22,272412481300040,885077001,0.008458,1,96
29410772,2020-07-24,272412481300040,850176003,0.029034,2,96
29410773,2020-07-24,272412481300040,875803001,0.064559,2,96
29410774,2020-07-24,272412481300040,892970003,0.020966,2,96
29410775,2020-07-24,272412481300040,854619003,0.020966,2,96
29531614,2020-07-27,272412481300040,900398001,0.030492,2,96
29531615,2020-07-27,272412481300040,834179002,0.025407,2,96
29531616,2020-07-27,272412481300040,875803001,0.067780,2,96
31495014,2020-09-14,272412481300040,923460002,0.039932,2,103
31495015,2020-09-14,272412481300040,922381001,0.039932,2,103
31495016,2020-09-14,272412481300040,921906005,0.031949,2,103

### Bestsellers candidates

In [213]:
mean_price = transactions \
    .groupby(['week', 'article_id'])['price'].mean()

In [214]:
mean_price

week  article_id
95    108775015     0.004729
      108775044     0.008458
      110065001     0.006085
      110065002     0.006085
      111565001     0.004288
                      ...
104   952267001     0.013732
      952938001     0.048651
      953450001     0.016932
      953763001     0.021885
      956217002     0.059068
Name: price, Length: 196880, dtype: float32

In [215]:
sales = transactions \
    .groupby('week')['article_id'].value_counts() \
    .groupby('week').rank(method='dense', ascending=False) \
    .groupby('week').head(12).rename('bestseller_rank').astype('int8')

In [216]:
sales

week  article_id
95    760084003      1
      866731001      2
      600886001      3
      706016001      4
      372860002      5
                    ..
104   915529003      8
      915529005      9
      448509014     10
      762846027     11
      714790020     12
Name: bestseller_rank, Length: 120, dtype: int8

In [217]:
sales.loc[95]

article_id
760084003     1
866731001     2
600886001     3
706016001     4
372860002     5
610776002     6
877278002     7
547780003     8
817354001     9
827968001    10
866731003    11
866383006    12
Name: bestseller_rank, dtype: int8

In [218]:
bestsellers_previous_week = pd.merge(sales, mean_price, on=['week', 'article_id']).reset_index()
bestsellers_previous_week.week += 1

In [219]:
bestsellers_previous_week.pipe(lambda df: df[df['week']==96])

    week  article_id  bestseller_rank     price
0     96   760084003                1  0.025094
1     96   866731001                2  0.024919
2     96   600886001                3  0.022980
3     96   706016001                4  0.033197
4     96   372860002                5  0.013193
5     96   610776002                6  0.008318
6     96   877278002                7  0.025036
7     96   547780003                8  0.024814
8     96   817354001                9  0.021913
9     96   827968001               10  0.016436
10    96   866731003               11  0.024893
11    96   866383006               12  0.023195

In [220]:
unique_transactions = transactions \
    .groupby(['week', 'customer_id']) \
    .head(1) \
    .drop(columns=['article_id', 'price']) \
    .copy()

In [221]:
unique_transactions

              t_dat           customer_id  sales_channel_id  week
29030503 2020-07-15       272412481300040                 1    95
29064059 2020-07-15      1456826891333599                 1    95
29067103 2020-07-15      2133687643102426                 2    95
29027487 2020-07-15      6010692573790711                 1    95
29046403 2020-07-15      6171059100114610                 2    95
...             ...                   ...               ...   ...
31760188 2020-09-22  18435221511488011015                 1   104
31782234 2020-09-22  18436859303155335645                 1   104
31787251 2020-09-22  18437941771381362708                 2   104
31776022 2020-09-22  18438270306572912089                 1   104
31779097 2020-09-22  18440902715633436014                 1   104

[755710 rows x 4 columns]

In [222]:
transactions.drop_duplicates(['week', 'customer_id'])

,t_dat,customer_id,article_id,price,sales_channel_id,week
29030503,2020-07-15,272412481300040,778064028,0.008458,1,95
29064059,2020-07-15,1456826891333599,888294001,0.013542,1,95
29067103,2020-07-15,2133687643102426,843642001,0.042356,2,95
29027487,2020-07-15,6010692573790711,857812010,0.039661,1,95
29046403,2020-07-15,6171059100114610,815447007,0.006763,2,95
...,...,...,...,...,...,...
31760188,2020-09-22,18435221511488011015,573085055,0.033881,1,104
31782234,2020-09-22,18436859303155335645,801447001,0.030492,1,104
31787251,2020-09-22,18437941771381362708,907188001,0.050831,2,104
31776022,2020-09-22,18438270306572912089,751471043,0.033881,1,104
31779097,2020-09-22,18440902715633436014,918894002,0.016932,1,104

In [223]:
candidates_bestsellers = pd.merge(
    unique_transactions,
    bestsellers_previous_week,
    on='week',
)

In [224]:
test_set_transactions = unique_transactions.drop_duplicates('customer_id').reset_index(drop=True)
test_set_transactions.week = test_week

In [225]:
test_set_transactions

            t_dat           customer_id  sales_channel_id  week
0      2020-07-15       272412481300040                 1   105
1      2020-07-15      1456826891333599                 1   105
2      2020-07-15      2133687643102426                 2   105
3      2020-07-15      6010692573790711                 1   105
4      2020-07-15      6171059100114610                 2   105
...           ...                   ...               ...   ...
437360 2020-09-22  18410229429441241008                 2   105
437361 2020-09-22  18417769707947924979                 2   105
437362 2020-09-22  18418054986721795659                 2   105
437363 2020-09-22  18421175435799911749                 2   105
437364 2020-09-22  18438270306572912089                 1   105

[437365 rows x 4 columns]

In [226]:
candidates_bestsellers_test_week = pd.merge(
    test_set_transactions,
    bestsellers_previous_week,
    on='week'
)

In [227]:
candidates_bestsellers = pd.concat([candidates_bestsellers, candidates_bestsellers_test_week])
candidates_bestsellers.drop(columns='bestseller_rank', inplace=True)

In [228]:
candidates_bestsellers

,t_dat,customer_id,sales_channel_id,week,article_id,price
0,2020-07-22,200292573348128,2,96,760084003,0.025094
1,2020-07-22,200292573348128,2,96,866731001,0.024919
2,2020-07-22,200292573348128,2,96,600886001,0.022980
3,2020-07-22,200292573348128,2,96,706016001,0.033197
4,2020-07-22,200292573348128,2,96,372860002,0.013193
...,...,...,...,...,...,...
5248375,2020-09-22,18438270306572912089,1,105,915529003,0.033439
5248376,2020-09-22,18438270306572912089,1,105,915529005,0.033417
5248377,2020-09-22,18438270306572912089,1,105,448509014,0.041630
5248378,2020-09-22,18438270306572912089,1,105,762846027,0.025005
5248379,2020-09-22,18438270306572912089,1,105,714790020,0.049951

1. # My code
First a bit of encoding. We will change the missing age value to the median.

In [229]:
# from sklearn.preprocessing import StandardScaler
# scaler = StandardScaler()
# scaler.fit_transform(train['age'])

ages_copy = customers[customers.age != -1].copy()
median_age = ages_copy['age'].median()
median_age

32.0

In [230]:
customers.loc[customers['age'] == -1] = median_age 
customers['age'].min()

16

## Most popular item types

In [231]:
# transactions.loc[:'year'] = transactions['t_dat'].dt.year
# transactions['year'].value_counts()

## Find the most bought color for a user
We want to know the favourite color of the user based on the items bought.

In [232]:
pop_colors = articles.groupby('colour_group_code')['article_id'].value_counts()

In [233]:
pop_colors

colour_group_code  article_id
-1                 592986010     1
                   662344003     1
                   665665001     1
                   694968001     1
                   694968004     1
                                ..
 93                936776001     1
                   937965001     1
                   942596001     1
                   946504001     1
                   947310001     1
Name: article_id, Length: 105542, dtype: int64

# Combining transactions and candidates / negative examples

In [234]:
transactions['purchased'] = 1

In [235]:
data = pd.concat([transactions, candidates_last_purchase, candidates_bestsellers])
data.purchased.fillna(0, inplace=True)

In [236]:
data

,t_dat,customer_id,article_id,price,sales_channel_id,week,purchased
29030503,2020-07-15,272412481300040,778064028,0.008458,1,95,1.0
29030504,2020-07-15,272412481300040,816592008,0.016932,1,95,1.0
29030505,2020-07-15,272412481300040,621381021,0.033881,1,95,1.0
29030506,2020-07-15,272412481300040,817477003,0.025407,1,95,1.0
29030507,2020-07-15,272412481300040,899088002,0.025407,1,95,1.0
...,...,...,...,...,...,...,...
5248375,2020-09-22,18438270306572912089,915529003,0.033439,1,105,0.0
5248376,2020-09-22,18438270306572912089,915529005,0.033417,1,105,0.0
5248377,2020-09-22,18438270306572912089,448509014,0.041630,1,105,0.0
5248378,2020-09-22,18438270306572912089,762846027,0.025005,1,105,0.0
5248379,2020-09-22,18438270306572912089,714790020,0.049951,1,105,0.0

In [237]:
data.drop_duplicates(['customer_id', 'article_id', 'week'], inplace=True)

In [238]:
data.purchased.mean()

0.13607582749165664

### Add bestseller information

In [239]:
data = pd.merge(
    data,
    bestsellers_previous_week[['week', 'article_id', 'bestseller_rank']],
    on=['week', 'article_id'],
    how='left'
)

In [240]:
data = data[data.week != data.week.min()]
data.bestseller_rank.fillna(999, inplace=True)

In [241]:
data = pd.merge(data, articles, on='article_id', how='left')
data = pd.merge(data, customers, on='customer_id', how='left')

In [242]:
data.sort_values(['week', 'customer_id'], inplace=True)
data.reset_index(drop=True, inplace=True)

In [243]:
# make a copy of the date column
# we use the date column to replace it with the days  so we still have the date, but now have a day column
data["day"] = data.loc[:,"t_dat"]
data.loc[:, "day"] = data["day"].dt.day
data["day"].value_counts()

22    820960
12    703357
5     676668
17    662884
29    660090
18    638632
4     630855
19    618459
20    617796
30    616189
24    605353
28    604178
27    603955
15    596516
21    593368
3     588707
6     587803
25    576484
23    572034
26    569438
16    529897
1     528727
7     527293
11    513680
13    512901
31    508048
10    505329
2     492914
9     454006
8     450461
14    424780
Name: day, dtype: int64

In [244]:
data["t_dat"].value_counts()

2020-08-12    437808
2020-08-05    388062
2020-07-30    387819
2020-07-29    381793
2020-07-22    381296
               ...
2020-07-20    154218
2020-07-18    154131
2020-09-15    152530
2020-08-16    146842
2020-07-19    105788
Name: t_dat, Length: 70, dtype: int64

In [245]:
data.loc[:, "day_sin"] = np.sin(2 * np.pi * data["day"]/365)
data["day_sin"]

0           0.432776
1           0.304921
2           0.304921
3           0.432776
4           0.432776
              ...
17991757    0.353676
17991758    0.353676
17991759    0.353676
17991760    0.353676
17991761    0.353676
Name: day_sin, Length: 17991762, dtype: float64

In [246]:
data.loc[:, "day_cos"] = np.cos(2 * np.pi * data["day"]/365)
data["day_sin"]

0           0.432776
1           0.304921
2           0.304921
3           0.432776
4           0.432776
              ...
17991757    0.353676
17991758    0.353676
17991759    0.353676
17991760    0.353676
17991761    0.353676
Name: day_sin, Length: 17991762, dtype: float64

In [247]:
train = data[data.week != test_week]
test = data[data.week==test_week].drop_duplicates(['customer_id', 'article_id', 'sales_channel_id']).copy()

In [248]:
train_baskets = train.groupby(['week', 'customer_id'])['article_id'].count().values

In [249]:
train['age'].min()

16.0

In [250]:
columns_to_use = ['article_id', 'product_type_no', 'graphical_appearance_no', 'colour_group_code', 'perceived_colour_value_id',
'perceived_colour_master_id', 'department_no', 'index_code',
'index_group_no', 'section_no', 'garment_group_no', 'FN', 'Active', 'day_sin', 'day_cos',
'club_member_status', 'fashion_news_frequency', 'age', 'postal_code', 'bestseller_rank']

In [251]:
%%time

train_X = train[columns_to_use]
train_y = train['purchased']

test_X = test[columns_to_use]

CPU times: user 490 ms, sys: 1.81 s, total: 2.3 s
Wall time: 2.29 s

# Model training

In [252]:
from lightgbm.sklearn import LGBMRanker

In [253]:
ranker = LGBMRanker(
    objective="lambdarank",
    metric="ndcg",
    boosting_type="dart",
    n_estimators=1,
    importance_type='gain',
    verbose=10
)

In [254]:
%%time

ranker = ranker.fit(
    train_X,
    train_y,
    group=train_baskets,
)

[LightGBM] [Debug] Dataset::GetMultiBinFromSparseFeatures: sparse rate 0.847172
[LightGBM] [Debug] Dataset::GetMultiBinFromAllFeatures: sparse rate 0.137457
[LightGBM] [Debug] init for col-wise cost 0.347661 seconds, init for row-wise cost 1.137588 seconds
[LightGBM] [Warning] Auto-choosing row-wise multi-threading, the overhead of testing was 0.777547 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Debug] Using Dense Multi-Val Bin
[LightGBM] [Info] Total Bins 1147
[LightGBM] [Info] Number of data points in the train set: 11381612, number of used features: 20
[LightGBM] [Debug] Trained a tree with leaves = 31 and depth = 9
CPU times: user 32.4 s, sys: 4.93 s, total: 37.3 s
Wall time: 15.6 s

In [255]:
for i in ranker.feature_importances_.argsort()[::-1]:
    print(columns_to_use[i], ranker.feature_importances_[i]/ranker.feature_importances_.sum())

bestseller_rank 0.9981467199313868
day_sin 0.0006905940517877345
garment_group_no 0.00046081500326484754
article_id 0.0002120355244853415
age 0.00014651611461363335
product_type_no 0.0001457956249235675
department_no 8.46014737370854e-05
section_no 7.06130584157759e-05
club_member_status 2.1436300463088474e-05
postal_code 2.0872916922079157e-05
day_cos 0.0
fashion_news_frequency 0.0
Active 0.0
FN 0.0
index_group_no 0.0
index_code 0.0
perceived_colour_master_id 0.0
perceived_colour_value_id 0.0
colour_group_code 0.0
graphical_appearance_no 0.0

# Calculate predictions

In [256]:
%time

test['preds'] = ranker.predict(test_X)

c_id2predicted_article_ids = test \
    .sort_values(['customer_id', 'preds'], ascending=False) \
    .groupby('customer_id')['article_id'].apply(list).to_dict()

bestsellers_last_week = \
    bestsellers_previous_week[bestsellers_previous_week.week == bestsellers_previous_week.week.max()]['article_id'].tolist()

CPU times: user 4 µs, sys: 1e+03 ns, total: 5 µs
Wall time: 9.06 µs

# Create submission

In [257]:
sub = pd.read_csv('/kaggle/input/h-and-m-personalized-fashion-recommendations/sample_submission.csv')

In [258]:
%%time
preds = []
for c_id in customer_hex_id_to_int(sub.customer_id):
    pred = c_id2predicted_article_ids.get(c_id, [])
    pred = pred + bestsellers_last_week
    preds.append(pred[:12])

CPU times: user 7.38 s, sys: 391 ms, total: 7.77 s
Wall time: 7.8 s

In [259]:
preds = [' '.join(['0' + str(p) for p in ps]) for ps in preds]
sub.prediction = preds

In [261]:
sub_name = 'added_2_features_model_submission'
sub.to_csv(f'{sub_name}.csv.gz', index=False)